### ISSUE TITLE
Add __eq__ method to Raster class

### ISSUE THREAD

**Issue by erikmannerfelt** [GlacioHack/GeoUtils#113]
Right now, the "==" operator works in a quite unexpected way:
```python
In [1]: raster = gu.georaster.Raster("examples/Longyearbyen/data/DEM_2009_ref.tif")

In [2]: raster2 = gu.georaster.Raster("examples/Longyearbyen/data/DEM_2009_ref.tif")

In [2]: raster == raster2
Out[2]: False
```
I would argue that the above comparison should be true. It could be by adding an `__eq__(self, other)` method to the Raster class. I think this would work (EDIT: It passes my test in the PR #114 ):

```python
def __eq__(self, other: Raster) -> bool:
    return all([
        np.array_equal(self.data, other.data, equal_nan=True),
        self.transform == other.transform,
        self.crs == other.crs,
        self.nodata == other.nodata
    ])
```
Other comparisons could be added, such as the `filename` and `matches_disk` attributes. I would argue that only the attributes in my example should be tested, because the others are unique to Rasters loaded from disk (would not work on a Raster made from `Raster.from_array()`).

Such an addition would also be great for testing purposes (see related discussions in xdem: [46](https://github.com/GlacioHack/xdem/pull/46) and [43](https://github.com/GlacioHack/xdem/issues/43), and #112 on geotuils):

```python
raster3 = raster2.copy()

assert raster3 == raster2  # This should pass (but won't right now)

raster3.data += 5

assert raster3 != raster2  # This should also pass (will right now, but not for the right reason!)
```

**Comment by rhugonnet** [comment]
Closed by #114
