### ISSUE TITLE
Download sample data rather than having in repo

### ISSUE THREAD

**Issue by adehecq** [GlacioHack/geoutils#117]
Similarly to xdem, we could have a script to download the data from archives, like google cloud?
Here's an example of link to Landsat image:
gdalinfo /vsicurl/https://storage.googleapis.com/gcp-public-data-landsat/LE07/01/140/041/LE07_L1TP_140041_20001030_20170209_01_T1/LE07_L1TP_140041_20001030_20170209_01_T1_B2.TIF

**Comment by erikmannerfelt** [comment]
Fun thing, this (or at least a highly related) issue just got much more important! The website of the Norwegian Polar Institute have started issuing 503s for the glacier outline dataset, so #265 (and probably all other tests) fail now!

**Comment by erikmannerfelt** [comment]
The servers are back now!
