### ISSUE TITLE
self.ds.tag()['AREA_OR_POINT'] gets updated into 'Area' when cropping (updating)

### ISSUE THREAD

**Issue by rhugonnet** [GlacioHack/geoutils#127]
see #120

**Comment by erikmannerfelt** [comment]
Could you elaborate on this, @rhugonnet ? In #265, I was very confused as to why the "Area" representation is hardcoded after certain operations.

**Comment by rhugonnet** [comment]
Some more details: when using the `crop()` function (and maybe others! might come from the `from_array`), the `self.ds.tag()['AREA_OR_POINT']` property of the Raster is updated into `Area` even if it was originally `Point`.

This might be problematic. So we need to check if:
- This is respecting the pixel position (i.e. shifting the grid by half a pixel), which would be fine.
- Overwriting the `AREA_OR_POINT` attribute without making any grid change, which would be a wrong behaviour.

**Comment by erikmannerfelt** [comment]
Thanks for the additional info!

Perhaps a test-driven approach could verify this: we write the tests with the expected outcome and see if the functionality fits?

**Comment by rhugonnet** [comment]
Yes! This thread is a bit old and I was not so familiar with Python tests at the time :laughing:

**Comment by erikmannerfelt** [comment]
Oh yeah, it's almost a year old! I went through old issues to see how many were solved by removing the memoryfile, and this caught my attention.
