### ISSUE TITLE
Add nodata as optional argument to Raster

### ISSUE THREAD

**Issue by erikmannerfelt** [GlacioHack/GeoUtils#130]
Quite often in my experience, the nodata value is either wrong or unset on a DEM that I get or create. Right now, if I'm not mistaken, the only way to fix this is:
```python
nodata_value = -3.40282347e+38
r = Raster("path/to/file")
r.data.mask = r.data == nodata_value
```
Of course this works, but it would be much quicker if `nodata=` could be given to the `Raster.__init__()` function

**Comment by adehecq** [comment]
No, we have the method set_ndv for that!

**Comment by erikmannerfelt** [comment]
Ah, I didn't know that! 

I still think it would be nice to have as an argument because it would reduce one line, but it's not as necessary as I thought, so I'll drop this.
