### ISSUE TITLE
Suggestion: Simplify imports to allow gu.Raster, gu.Vector, and gu.SatelliteImage

### ISSUE THREAD

**Issue by erikmannerfelt** [GlacioHack/GeoUtils#141]
As mentioned in the title, this is a suggestion that I would love to discuss. Right now, I see two different ways that we use to import geoutils:

```python
from geoutils import georaster as gr
from geoutils import geovector as gv
from geoutils import satimg as # what exactly?

r = gr.Raster("path/to/raster.tif")
v = gv.Vector("path/to/vector.shp")
```
or 
```python
import geoutils as gu

r = gu.georaster.Raster("path/to/raster.tif")
v = gu.geovector.Vector("path/to/vector.shp")
```

Looking at other packages, I see the former approach (importing submodules with aliases) more rarely than the latter (importing the main module with an alias):
```python
import pandas as pd
import numpy as np

df = pd.DataFrame(...)
arr = np.array(...)
```
### My suggestion
you might see where I'm getting at now; what if we embrace the following syntax:
```python
import geoutils as gu

r = gu.Raster("path/to/raster.tif")
v = gu.Vector("path/to/vector.shp")
img = gu.SatelliteImage("path/to/img.tif")
```
This could be done with a quite simple fix to `geoutils/__init__.py`:
```python
from geoutils.georaster import Raster
from geoutils.geovector import Vector
from geoutils.satimg import SatelliteImage
```
which would make all of the above approaches work, including the (arguably) simplest suggestion just above. [We recently agreed on a very similar approach in xdem](https://github.com/GlacioHack/xdem/pull/42#issuecomment-802822675).

I see lots of pros with this approach, by making the syntax a bit easier. Are there any cons? I'd love to discuss this.

**Comment by adehecq** [comment]
I don't see any cons right now and probably a good idea.
The former import will still work anyway, so this should not introduce bugs.

**Comment by erikmannerfelt** [comment]
Exactly. I think the biggest pro is making it more newbie friendly, which is more or less one of our two primary goals with this entire project (the other being performant functionality), right?

**Comment by rhugonnet** [comment]
I support this 100%, I was actually thinking about the same thing at some point last week.
