### ISSUE TITLE
Use rasterio's read/write masks

### ISSUE THREAD

**Issue by adehecq** [GlacioHack/geoutils#151]
**Is your feature request related to a problem? Please describe.**
Currently, masking is only handled by nodata. This can be a problem for example for uint8 arrays, for which it might not be possible to "waste" a value.

**Describe the solution you'd like**
We could use an additional channel for masking, using rasterio's functionality: https://rasterio.readthedocs.io/en/latest/topics/masks.html
This would require calling read_mask and save_mask whenever needed.

**Describe alternatives you've considered**
None

**Comment by atedstone** [comment]
Masking now implemented(#235, #271)
