### ISSUE TITLE
Allow `Raster.from_array` and `Raster.split_bands()` to work without copying.

### ISSUE THREAD

**Issue by erikmannerfelt** [GlacioHack/GeoUtils#159]
Right now, `Raster.from_array()` always returns a copy of the data that are given. This is most often the wanted behaviour, but there may be cases when this is not sought. The method should optimally have a `copy` attribute which defaults to `True`.

A case where this would be nice is with the `Raster.split_bands()` method (which calls `Raster.from_array()` and is therefore dependent on its copy-ness):
```python
rgb = gu.Raster(datasets.get_path("landsat_RGB"))

red = rgb.split_bands(copy=False)[0]  # copy=False could be the default here.

red.data += 1  # Modify the red channel (it should also modify the rgb image)
assert np.array_equal(red.data, rgb.data[0, :, :])  # This should pass.

```

**Comment by adehecq** [comment]
I believe this will be really difficult by design, because from_array creates a memory file, which need to have the data saved in itself.
This is probably a deeper level issue with rasterio...
