### ISSUE TITLE
`Raster.crop()` does not work properly

### ISSUE THREAD

**Issue by erikmannerfelt** [GlacioHack/GeoUtils#176]
**Describe the bug**
If I'm not mistaken, `Raster.crop()` does not crop the file in a way that is expected.

**To Reproduce**
```python
In [1]: import geoutils as gu

In [2]: large_img = gu.Raster(gu.datasets.get_path("landsat_B4"))

In [4]: small_img = gu.Raster(gu.datasets.get_path("landsat_B4_crop"))

In [5]: large_img.shape, small_img.shape
Out[5]: ((655, 800), (174, 726))

In [6]: large_img.data.shape, small_img.data.shape
Out[6]: ((1, 655, 800), (1, 174, 726))

In [7]: large_img.crop(small_img)

In [8]: large_img.shape, small_img.shape
Out[8]: ((174, 598), (174, 726))

In [9]: large_img.data.shape, small_img.data.shape
Out[9]: ((1, 174, 598), (1, 174, 726))
```

**Expected behavior**
`large_img` and `small_img` should have the same shape after `crop()` is called.

**System (please complete the following information):**
 - OS: irrelevant
 - Environment conda

**Comment by erikmannerfelt** [comment]
Uuugh! Turns out the cropped Landsat image's bounds are larger eastward than the uncropped version! That's why the shapes become different!!

Then there's a question of if `crop()` should pad the data to fit another raster in the same grid, or if the current implementation is what we want? What do you think, @adehecq and @atedstone?

**Comment by adehecq** [comment]
> Uuugh! Turns out the cropped Landsat image's bounds are larger eastward than the uncropped version! That's why the shapes become different!!
> 
Damn! This should be a bug. I'll add it to the list.

> Then there's a question of if `crop()` should pad the data to fit another raster in the same grid, or if the current implementation is what we want? What do you think, @adehecq and @atedstone?

I think an option to add padding could be useful in some cases yes.
