### ISSUE TITLE
Add easier creation options for `Raster.save()`

### ISSUE THREAD

**Issue by erikmannerfelt** [GlacioHack/GeoUtils#178]
Many argue that compression should be used in every case today, as read/write algorithms are often as fast or faster than the disk itself. Therefore, `Raster.save()` should make it more user-frendly to specify compression. I would argue that it should also be on by default!

`rio.open` has two kwargs when writing that should be more obvious in geoutils:
1. `compress="deflate"` or any other compression algorithm. Equates to the COMPRESS=DEFLATE co
2. `tiled=False` or `True`. Equates to the TILED=YES / TILED=NO co

I know that these can be given as GDAL-like arguments with `co_opts` (creation option options? ;) ), but for a non-GDAL person, this is very far from obvious.

Finally, I think a compression algorithm should be default, and I propose deflate, as it works okay with every dtype that I know of.

**Comment by rhugonnet** [comment]
Agreed, and `DEFLATE` is really the best performing (compared to `LWZ`, for instance) when it comes to rasters with a lot of no data values (most satellite data).
I haven't tested `PACKBITS` though, that might perform well with nodata values too.
