### ISSUE TITLE
Change default branch name to `main`

### ISSUE THREAD

**Issue by erikmannerfelt** [GlacioHack/GeoUtils#180]
As mentioned by multiple sources, including the [Software Freedom Concervancy](https://sfconservancy.org/news/2020/jun/23/gitbranchname/), `master` is an outdated term with unnecessary links to politically loaded topics. This is an easy fix and we have no excuse to not change the default branch name to `main`.

In addition, it will make GeoUtils more consistent with xdem, as mentioned by @adehecq.

There is not a single place in the code that I know of which refers to the branch name, so this is as simple as just cloning the `master` branch and setting the `main` branch as default. In xdem, the GeoUtils download calls have to be changed accordingly, and ReadTheDocs might need to have its default branch updated.

**Comment by fmaussion** [comment]
https://github.com/github/renaming I think renaming is less intrusive

**Comment by erikmannerfelt** [comment]
Oops, turns out I don't have the privileges to change the branch name! Could you do it for example, @adehecq, or provide me the right rights?

We have explicit or implicit approval from @fmaussion, @adehecq, @iamdonovan and @atedstone from the slack channel, so I suggest we pull the bandage or whatever it's called in English and do it as soon as possible.

**Comment by erikmannerfelt** [comment]
I just changed the name to `main`
