### ISSUE TITLE
Include a "buffer" option in create_mask

### ISSUE THREAD

**Issue by adehecq** [GlacioHack/GeoUtils#193]
Currently, Vector.create_mask will use the raw mask. It would be nice to have an option to automatically create a buffer around the mask, using either scipy's or opencv's morphological dilation.

**Comment by adehecq** [comment]
Here's a quick example on how to do it:
```
from scipy.ndimage import morphology
import numpy as np

# Create a single 1 pixel within 0s
mask = np.zeros((11, 11))
mask[5, 5] = 1

# Dilate the mask with a buffer of size 2
buffer_size = 2
struct = np.ones((buffer_size*2 +1, buffer_size*2 + 1))
dil_mask = morphology.binary_dilation(mask, structure=struct)

```

Would be interesting to see how it compares with opencv's.

**Comment by rhugonnet** [comment]
The issue I see here is that the buffer will be "limited" by the resolution of your raster.
Wouldn't it make more sense to apply a `.buffer()` to the Vector object, and then rasterize it? The buffer functions run hyper fast, even on a shapefile with hundreds of thousands of geometries!

**Comment by adehecq** [comment]
> The issue I see here is that the buffer will be "limited" by the resolution of your raster.
> Wouldn't it make more sense to apply a `.buffer()` to the Vector object, and then rasterize it? The buffer functions run hyper fast, even on a shapefile with hundreds of thousands of geometries!

Good point! I didn't think it could be that fast, but if so, yes that's a good idea.
