### ISSUE TITLE
Update the release schedule

### ISSUE THREAD

**Issue by erikmannerfelt** [GlacioHack/geoutils#200]
The current release schedule is outdated and looks very complicated! There should be a description of what to do, and then a description of what all the workflows do automatically.

**Comment by rhugonnet** [comment]
Closed by #398

**Comment by adehecq** [comment]
I don't really get how #398 addresses the issue raised. We currently don't have a release **schedule** do we? We should definitely try to have one...

**Comment by rhugonnet** [comment]
Ah, I thought this was about the HOW_TO_RELEASE file @erikmannerfelt? (you discuss the "current" schedule)

It could be nice to add a "roadmap" in the documentation, but we'd need to discuss it in a separate doc first!

**Comment by rhugonnet** [comment]
Closing this as I think it's about the HOW_TO_RELEASE file (I let @erikmannerfelt say if not)
