### ISSUE TITLE
Simplify Raster.reproject

### ISSUE THREAD

**Issue by adehecq** [GlacioHack/geoutils#212]
We could use the functionality in rasterio.warp.calculate_default_transform to make the calculation of the transform easier in Raster.reproject (I should have seen that earlier...):
https://rasterio.readthedocs.io/en/latest/api/rasterio.warp.html#rasterio.warp.calculate_default_transform

SOme additional details from the rasterio [discussion group](https://rasterio.groups.io/g/main/message/786): "The intent is that rasterio.warp.reproject, given the values output from calculate_default_transform, will produce a result close to that of GDAL's gdalwarp utility *without* its "-tap" option. And that if you wrap the output of calculate_default_transform with aligned_target, adding a resolution, you will get a result close to that of gdalwarp *with* its "-tap" option."

**Comment by adehecq** [comment]
This is actually a bit more complex than anticipated, as the functions `calculate_default_transform` and `aligned_target` only take into account the input transform, width and height, but not the output bounds.
Obtaining a result similar to what is done in reproject for now (and similar to gdalwarp), but using rasterio's functions seem non trivial for now.

**Comment by adehecq** [comment]
GDAL's logic for default warping options is coded around here https://github.com/OSGeo/gdal/blob/d01976cd4fc11144662f44ec4e658ce1871f1713/gdal/apps/gdalwarp_lib.cpp#L3105

**Comment by rhugonnet** [comment]
I might add here that #354 is still an issue with our current method when passing `dst_bounds` and `dst_res` (or `dst_size`) individually. See #356
