### ISSUE TITLE
Add numpy plugin for mypy

### ISSUE THREAD

**Issue by erikmannerfelt** [GlacioHack/GeoUtils#224]
I'm sure we've all faced some related issue by now, and I think it's a pretty easy fix.

Without the numpy plugin, all `np.ndarray`s and friends evaluate to `Any` in `mypy`s eyes. Enabling the mypy numpy plugin and then fixing some type annotations should fix this.

**Comment by erikmannerfelt** [comment]
After tons of research, I've found that this only works properly with numpy>=1.20... This conflicts with the aim of #207  which is to keep backward compatibility with numpy!

What are your thoughts on backward compatibility, @rhugonnet @adehecq @atedstone.

For context, numpy 1.20 was released on 30 January 2021

**Comment by adehecq** [comment]
I think allowing only numpy > 1.20 might be quite limiting and could conflict with other libraries. So I would be in favor of keeping backward compatibility, especially since this is needed *only* for mypy and not for a core functionality.
Would your ArrayLike type in #227 solve the issue?

**Comment by erikmannerfelt** [comment]
Solutions like the `ArrayLike` in #227 would more or less solve the issue, yes!

**Comment by erikmannerfelt** [comment]
I now added the `_typing.py` module in #227, so I'll close this, as it is more or less not necessary anymore!

In maybe two years, we could reopen the issue to consider stricter numpy types...
