### ISSUE TITLE
Raster.save does not take into account mask.

### ISSUE THREAD

**Issue by adehecq** [GlacioHack/GeoUtils#233]
**Describe the bug**
When modifying the mask of a raster, without setting the corresponding values to nodata, the mask is not taken into account upon saving.

**To Reproduce**
```
import numpy as np
import geoutils as gu
# Load data
r = gu.Raster(gu.datasets.get_path('landsat_B4'))
outlines = gu.Vector(gu.datasets.get_path('glacier_outlines'))
# Mask glaciers
glacier_mask = outlines.create_mask(r)
r.data[glacier_mask] = np.ma.masked
# Check that it worked and save
r.show()
r.save('test.tif')
# Load the saved raster and check that masked values have been ignored
test = gu.Raster('test.tif')
test.show()
```

**Expected behavior**

Saved raster should have masked values set to nodata.

**Ideas of solution**

There are several options:
1) apply mask to both masked values and nodata values
2) raise a warning if mask and nodata disagree, then 1) 
3) raise an error if mask and nodata disagree
What do you think @atedstone @erikmannerfelt ?

**Comment by erikmannerfelt** [comment]
That's definitely not optimal! Another thing that's been bugging me for a long while is that rasterio and gdal don't really agree on `nan` handling. Some GDAL calculations don't work at all with nans, right? They "are supposed to have a nodata value", so mixing nodata with nan (and then the mask on top!) makes a true mess.

One solution would be to add a keyword argument to `Raster.save()` that does "convert all nans to the nodata value (if any)" which is True by default (so it can be disabled if you know what you're doing).

So my suggestion would be:
1. Convert the mask AND `nan`s to the nodata value. (default behavior)
2. Skip the `nan` check but trigger a warning (or raise an error, but I'd prefer warning) if the mask is inconsistent. (this behavior is triggered with a keyword argument)

**Comment by atedstone** [comment]
I'm not really got experience with (GDAL-)masked rasters, so cannot comment in detail here. But, I think that @erikmannerfelt 's development of the proposed options sounds like a good way forward.
