### ISSUE TITLE
Consistent masking of Raster object

### ISSUE THREAD

**Issue by rhugonnet** [GlacioHack/GeoUtils#235]
Implement a consistent way of masking Raster objects, to ensure codes are easily reproducible with ndarray, masked arrays and Raster subclasses.
See below.

It's bad practice to use NaNs with the masked arrays. The values should be masked instead. I just read on the numpy.ma module that the best way to do it is
```
dh.data[mask_glacier] = np.ma.masked
```
The only issue is that dh.data.data is unchanged, so if one were e.g. to save the new array, the mask would not be preserved. To ensure that, one must also change the data attribute:
```
dh.data.data[mask_glacier] = dh.nodata
```
Which is not very intuitive I must admit.

_Originally posted by @adehecq in https://github.com/GlacioHack/xdem/pull/159#discussion_r678332285_

**Comment by adehecq** [comment]
This is quite related to #233. I think it should just be masked as suggested in the first example. The second line is actually only needed because save does not take into account the mask, only the nodata value.

**Comment by rhugonnet** [comment]
Yes, but the issue I see is that probably less than 5% of programmers will know that the first example is the way to go, it's really not intuitive/widely used.

Maybe we should encapsulate this in the `data.setter`? 
And, for instance, if the users is calling `dh.data = np.nan`, then we run the first example? There could be a couple convenient cases where we update the mask like this?

**Comment by adehecq** [comment]
Well, we should make it clear somewhere in the documentation.
I don't think the data.setter is used when changing only a view of self.data (e.g. `self.data[mask] = 0`) but only when updating the whole attribute (e.g. `self.data = np.zeros((10, 10))`) but I'll double check.

**Comment by adehecq** [comment]
Another option that came to my mind is to create a method like `gu.Raster.mask` that reads in a boolean array and does the masking. This would be more intuitive than having to edit `self.data.mask`.
