### ISSUE TITLE
`Raster.reproject()` raises confusing error when data are not loaded

### ISSUE THREAD

**Issue by erikmannerfelt** [GlacioHack/GeoUtils#238]
**Describe the bug**
If the data are not loaded before calling reproject, it fails. The error is also not very useful...

**To Reproduce**
```python
import geoutils as gu

img1 = gu.Raster(gu.datasets.get_path("landsat_B4_crop"), load_data=True)
img2 = gu.Raster(gu.datasets.get_path("landsat_B4"), load_data=False)

img2.crop(img1)

#img2.load()

img2_reproj = img2.reproject(img1)
```
This raises an exception:
```
Traceback (most recent call last):
  File "/home/erik/temp/hello.py", line 8, in <module>
    img2_reproj = img2.reproject(img1)
  File "/home/erik/Projects/ETH/GeoUtils/geoutils/georaster.py", line 1022, in reproject
    dst_data, dst_transformed = rio.warp.reproject(self.data, **reproj_kwargs)
  File "/home/erik/.local/share/conda/geoutils/lib/python3.9/site-packages/rasterio/env.py", line 387, in wrapper
    return f(*args, **kwds)
  File "/home/erik/.local/share/conda/geoutils/lib/python3.9/site-packages/rasterio/env.py", line 610, in wrapper
    return f(*args, **kwds)
  File "/home/erik/.local/share/conda/geoutils/lib/python3.9/site-packages/rasterio/warp.py", line 368, in reproject
    _reproject(
  File "rasterio/_warp.pyx", line 410, in rasterio._warp._reproject
  File "rasterio/_warp.pyx", line 404, in rasterio._warp._reproject
ValueError: Invalid source
```
I presume what the error means is that `None` is an invalid source.

If `img2.load()` is uncommented in the above example, reprojection works fine.

**Expected behavior**
Like most other parts of the `Raster` class, `Raster._data` should probably be silently loaded in the `reproject()` function. An alternative (but I think much worse) solution is to just provide an actual descriptive error.

**System (please complete the following information):**
 - OS: Linux
 - Environment: latest main

**Additional context**
The reason I found this, and also why it bothers me, is that I often have a large reference DEM that I want to compare with a smaller DEM. Then I could do something like:
```python
small_dem = xdem.DEM("...")
# Crop the DEM first and then use `reproject()` to conform the resolution.
large_dem = xdem.DEM("...", load_data=False).crop(small_dem, inplace=False)
large_dem.load()
large_dem = large_dem.reproject(small_dem, resample="bilinear")
```
This could have been made in a one-liner, if this "bug" is fixed:
```python
small_dem = xdem.DEM("...")
# Crop the DEM first and then use `reproject()` to conform the resolution.
large_dem = xdem.DEM("...", load_data=False).crop(small_dem, inplace=False).reproject(small_dem, resample="bilinear")
```
This gets me thinking that maybe the `Raster()` instantiation could have a crop functionality already. Something like:
```python
large_dem = xdem.DEM("...", crop_to=small_dem)
```
... which would open the dataset, crop it, and then load the data.

**Comment by adehecq** [comment]
You mean, some easy fix like this: https://github.com/GlacioHack/GeoUtils/pull/126/files? 😉 
I would favor simply raising an error. Overall, I'm not a big fan of the functions silently loading potentially GB of data in memory. I don't think it is that bad to have an additional line that **explicitely** loads the data when needed.

I also understand your frustration with the example shown, but I feel like 3 lines of code is not that bad! I find the one-liner example actually less easy to understand. We could possibly include a cropping option to the instantiation (I'm 99% sure it was part of the older geoutils, although with an unclear argument `load_data` that could be a boolean or a 4-tuple). The only risk I see is that if we duplicate functionalities, users might be confused... So at least the crop option should have the same arguments as the crop method and simply call the method underneath.

**Comment by rhugonnet** [comment]
Agree with Amaury in that raising an error seems to be the preferable behaviour to me (after all, one has to specify `load_data=False`, so must expect to have different behaviour from that point on)
