### ISSUE TITLE
`Raster`/`Vector` instantiation does not accept `pathlib.Path` filenames

### ISSUE THREAD

**Issue by erikmannerfelt** [GlacioHack/geoutils#239]
**Describe the bug**
`pathlib` makes handling of paths a little easier. This package is well established (and part of the stdlib), but it is not supported as a `filename` to a new `Raster`.

**To Reproduce**
```python
import geoutils as gu
import pathlib

path = pathlib.Path(gu.datasets.get_path("landsat_B4"))

img = gu.Raster(path)
```
This fails with the error: 
```
Traceback (most recent call last):
  File "/home/erik/temp/hello.py", line 6, in <module>
    img = gu.Raster(path)
  File "/home/erik/Projects/ETH/GeoUtils/geoutils/georaster.py", line 251, in __init__
    raise ValueError("filename argument not recognised.")
ValueError: filename argument not recognised.
```

**Expected behavior**
All different `pathlib` path objects should be supported (they are by rasterio, so this should be an easy fix).

**System (please complete the following information):**
 - OS: Linux
 - Environment : latest main

**Comment by erikmannerfelt** [comment]
A potential fix is to just call `str(filename)` somewhere in the instantiation. Then the path would be converted to a "path string"

**Comment by erikmannerfelt** [comment]
I just saw that this is an issue for `Vector`s!

**Comment by adehecq** [comment]
What is the use for pathlib? But sure, if it all comes down to making sure the path is converted to string before being passed, it should be an easy fix.

**Comment by rhugonnet** [comment]
Seems like an easy fix :+1:
