### ISSUE TITLE
`Raster.reproject()` fails on 4-band rasters

### ISSUE THREAD

**Issue by erikmannerfelt** [GlacioHack/geoutils#242]
**Describe the bug**
When `reproject()` is run on a 4-band raster (in my case RGB + mask), it fails. This is an easy fix, however.

**To Reproduce**
```python
import geoutils as gu
import rasterio as rio
import numpy as np

img1 = gu.Raster.from_array(
        np.ones((4, 500, 500), dtype="uint8"),
        transform=rio.transform.from_origin(0, 500, 1, 1),
        crs=4326
)

img2 = gu.Raster.from_array(
        np.ones((4, 500, 500), dtype="uint8"),
        transform=rio.transform.from_origin(50, 500, 1, 1),
        crs=4326
)

img2.reproject(img1)


```
This raises the error:
```
Traceback (most recent call last):
  File "/home/erik/temp/hello.py", line 19, in <module>
    img2.reproject(img1)
  File "/home/erik/Projects/ETH/GeoUtils/geoutils/georaster.py", line 1022, in reproject
    dst_data, dst_transformed = rio.warp.reproject(self.data, **reproj_kwargs)
  File "/home/erik/.local/share/conda/geoutils/lib/python3.9/site-packages/rasterio/env.py", line 387, in wrapper
    return f(*args, **kwds)
  File "/home/erik/.local/share/conda/geoutils/lib/python3.9/site-packages/rasterio/env.py", line 610, in wrapper
    return f(*args, **kwds)
  File "/home/erik/.local/share/conda/geoutils/lib/python3.9/site-packages/rasterio/warp.py", line 368, in reproject
    _reproject(
  File "rasterio/_warp.pyx", line 473, in rasterio._warp._reproject
  File "rasterio/_warp.pyx", line 429, in rasterio._warp._reproject
ValueError: Invalid destination shape
```

**Expected behavior**
This should not fail. It's a simple and easy to fix bug.

**Additional context**
The line that messes things up is:
https://github.com/GlacioHack/GeoUtils/blob/314764147b84e1680868d512f1195feda46e094c/geoutils/georaster.py#L984

If this is changed to:
```python
dst_data = np.ones((self.nbands, dst_size[1], dst_size[0]), dtype=dtype) 
```
... everything works as expected!

Makes me wonder, however, why that array is even necessary?? It's given as the `"destination"` argument to `rio.warp.reproject()`, but it's not used after that (the returned array from the call is used). Are these the same objects, only with different names? Or is the entire array duplicated??

We should validate that `destination` and `dst_data` is actually the same array:
https://github.com/GlacioHack/GeoUtils/blob/314764147b84e1680868d512f1195feda46e094c/geoutils/georaster.py#L1022

**Comment by adehecq** [comment]
Good catch!
To reply to your question, if you check rio.warp.reproject's [documentation](https://rasterio.readthedocs.io/en/latest/api/rasterio.warp.html), there is no other way to set the output raster width/height than to feed in an array of the correct shape. So dst_data is used whenever it is needed to enforce the output shape. If you find a better way, let me know!

**Comment by atedstone** [comment]
The fix for this needs to include uncommenting the 3-d test cases for `test_merge_rasters` and `test_stack_rasters` in `test_spatial_tools.py` (PR #253 ).
