### ISSUE TITLE
Test python 3.10 (and 3.11?) in CI

### ISSUE THREAD

**Issue by erikmannerfelt** [GlacioHack/geoutils#266]
Python 3.10 is now bundled in most distributions, and we should make sure that it works properly. Maybe it doesn't make sense to test four versions, so I suggest these:

- python 3.7 (for compatibility)
- python 3.9 (many will still use this)
- python 3.10 (all new users will use this)

Many will of course also be on 3.8, but if it works on 3.7 and 3.9, it probably works for 3.8 too.

A heads-up in case I'm not the one implementing this:
- rasterio 1.2 does not work with 3.10! rio 1.3 will work, and their latest master works, but the 1.3a2 does not. https://github.com/rasterio/rasterio/commit/329c481bfdad4fa3272d07a548001f5ec1e8bda4 fixed this on 26 November 2021, so any release after that should work.
- I've also had issues with fiona. This was also fixed (https://github.com/Toblerity/Fiona/commit/3b1e80bfba017651151942b46fa1744e7fee6842; 22 November 2021), but has not yet been found in a release.

**Comment by erikmannerfelt** [comment]
In addition, it would be great to somehow stay ahead of the curve and test python 3.11 as well! (It's in alpha 3 at the time of writing)

**Comment by adehecq** [comment]
Decided to add 3.10 but to include 3.11 only when it is stable.
