### ISSUE TITLE
Fix issues in from_array

### ISSUE THREAD

**Issue by adehecq** [GlacioHack/geoutils#282]
Despite our best efforts, PR #265 seems to have introduced bugs that are not caught by current tests.
The backbone is in `from_array` and some checks seem to have been lost in the PR after [this line](https://github.com/GlacioHack/GeoUtils/pull/265/files#diff-706a5e63234acd08def533a19aae4dc002438ad09b809802ddd09b1d51dff280L333), e.g.:
- [ ] the dimension of data is not forced to be 3D (as in rasterio)
- [ ] the mask is likely not always preserved

**Comment by rhugonnet** [comment]
Also potentially after [this line](https://github.com/GlacioHack/GeoUtils/pull/265/files#diff-706a5e63234acd08def533a19aae4dc002438ad09b809802ddd09b1d51dff280L769) of `_update`, that doesn't exist anymore.

**Comment by adehecq** [comment]
Actually, the issue does not seem to be in `from_array`, or at least I was not able to find one. But an issue occurs with reproject for rasters with masked values, e.g.:
```
import geoutils as gu
# Take any raster with gaps
r = gu.Raster('/Users/adehecq/work/RAGMAC/ragmac_xdem/data/raw/experiment_2/PK_Baltoro/DEM_2002.75631975.tif')
r2 = r.reproject(dst_res=20)
print(r2.data)
print(r.data)
```
-> `r2.data` and `r.data` have different fill_value. This might cause issues later.

**Comment by rhugonnet** [comment]
Maybe the added lines in `reproject` [here](https://github.com/GlacioHack/GeoUtils/pull/265/files#diff-706a5e63234acd08def533a19aae4dc002438ad09b809802ddd09b1d51dff280R1243)?
More tomorrow...
