### ISSUE TITLE
`Raster.crop()` has an erroneous right bound

### ISSUE THREAD

**Issue by rhugonnet** [GlacioHack/geoutils#287]
Looks like the right bound of `crop` is shifted by exactly one pixel. This was hidden because the tests could not check this bound due to #190.

The test is skipped starting in #284 as it fails:

```python
r = gr.Raster(landsat_b4_path)
r2 = gr.Raster(landsat_b4_crop_path)

# Get expected bounds
b = r.bounds
b2 = r2.bounds
b_minmax = (max(b[0], b2[0]), max(b[1], b2[1]), min(b[2], b2[2]), min(b[3], b2[3]))

# Crop to the smaller extent
r.crop(r2)

assert b_minmax == b_crop
[Out]: False
```
`r.bounds.right[2]` is shifted by 30 (= 1 pixel) compared to `r2.bounds.right[2]` which it should have been cropped to.

**Comment by adehecq** [comment]
I don't see the issue. 
First, there is a line missing in your example, what is `b_crop`?
If I run this on my install, I get:

> In [30]: print(r.bounds)
> BoundingBox(left=484060.0, bottom=3098030.0, right=502000.0, top=3103250.0)
> 
> In [31]: print(b_minmax)
> (484060.0, 3098030.0, 502000.0, 3103250.0)
>
> In [35]: list(r.bounds) == list(b_minmax)
> Out[35]: True

So exactly the same...
