### ISSUE TITLE
Method to return coordinates of all pixels

### ISSUE THREAD

**Issue by atedstone** [GlacioHack/GeoUtils#29]
e.g. georaster.coordinates(), potentially geoimg.xy()

**Comment by atedstone** [comment]
From the docstring of rioxarray.open_rasterio:

```
You can generate 2D coordinates from the file's attributes with::

    from affine import Affine
    da = xr.open_rasterio('path_to_file.tif')
    transform = Affine.from_gdal(*da.attrs['transform'])
    nx, ny = da.sizes['x'], da.sizes['y']
    x, y = np.meshgrid(np.arange(nx)+0.5, np.arange(ny)+0.5) * transform
```

**Comment by adehecq** [comment]
Nice! We should then just write the function with these commands.
I just don't understand the need for `Affine.from_gdal(*da.attrs['transform'])`. We could use ds.transform directly no? And ds.width/height.
