### ISSUE TITLE
Deprecate `gu.misc.array_equal` for `np.array_equal` and enforce Numpy>1.19

### ISSUE THREAD

**Issue by rhugonnet** [GlacioHack/geoutils#290]
The `equal_nan` functionality of `np.array_equal` was introduced in NumPy 1.19.0, compatible with Python 3.6.
It was relevant to have this for backward compatibility a year ago when it was relatively new (see #227), but now we only use Python >3.7 (soon >3.8) anyway, so NumPy will always be >1.19.
We can deprecate `gu.misc.array_equal` and switch fully to `np.array_equal` for simplicity.

_Originally posted by @rhugonnet in https://github.com/GlacioHack/geoutils/pull/289#discussion_r958390156_

**Comment by adehecq** [comment]
According to the docstring of `gu.misc.array_equal`, there are other functionalities that may not exist in `np.array_equal` like:
- different dtypes are ok
- masked_array's masks are taken into account
- a tolerance is allowed

We could test, but I don't think these exist in numpy's.

**Comment by rhugonnet** [comment]
Actually this exists as `np.ma.allequal`.
