### ISSUE TITLE
Ensure that masked values are always set to nodata in Raster

### ISSUE THREAD

**Issue by adehecq** [GlacioHack/geoutils#292]
At many occasions, one can update the mask in `Raster.data` but the underlying values are unchanged.
This can lead ton inconsistencies when `self.data.data` is read, e.g. by other modules like rasterio. It would probably be safer to always update the values in `self.data.data`.
The first thing is to modify `set_mask` to ensure that. It will require setting a nodata value in all cases though, is that desired?

Here is a draft of set_mask:

```
    def set_mask(self, mask: np.ndarray, nodata: int | float | None = None) -> None:
        """
        Mask all pixels of self.data where `mask` is set to True or > 0.

        Masking is performed in place.
        `mask` must have the same shape as loaded data, unless the first dimension is 1, then it is ignored.

        :param mask: The data mask
        :param nodata: The nodata value to be used (by default uses self.nodata)
        """
        # Check that mask is a Numpy array
        if not isinstance(mask, np.ndarray):
            raise ValueError("mask must be a numpy array.")

        # Check that new_data has correct shape
        if self.is_loaded:
            orig_shape = self.data.shape
        else:
            raise AttributeError("self.data must be loaded first, with e.g. self.load()")

        if mask.shape != orig_shape:
            # In case first dimension is empty and other dimensions match -> reshape mask
            if (orig_shape[0] == 1) & (orig_shape[1:] == mask.shape):
                mask = mask.reshape(orig_shape)
            else:
                raise ValueError(f"mask must be of the same shape as existing data: {orig_shape}.")

        # Check that a nodata value is set, otherwise, need to set one
        # It should not be needed, but some functionnalities like rasterio's reproject require a nodata to be set.
        if self.nodata is None:
            if nodata is None:
                raise ValueError("A nodata must be set. Use self.set_ndv()")
            else:
                self.nodata = nodata

        # Mask array
        self.data[mask > 0] = np.ma.masked

        # Replace the masked values by nodata
        self.data = self.data.filled(self.nodata)
```

**Comment by rhugonnet** [comment]
**Adapted from a comment in #300 for the record:**
My opinion would be to not address this issue at all: if one wants to work with a nodata-proof array, he can (1) use directly the masked array in `.data` or (2) use `get_nanarray()` to get a NaN array, or (3) run his calculation directly on the Raster object once I have fixed the `array_interface` to apply to the masked array.

We use to work with `.data.data` at the beginning, but we should not anymore, especially with the numpy array interface!

**Comment by rhugonnet** [comment]
@adehecq Should we close this? I'm not sure we want to force values that are masked as nodata for many reasons (different types of masking super-imposed): 

- if we want to keep masking the Raster for other reasons (unstable terrain), 
- if we want to find the non-finite values in the data compared to nodata values for debugging reasons.

The comment above lists the 3 options for manipulating the data safely (ideally, `.data.data` should never be modified manually except for expert use).

But I'm thinking maybe we should have a function `reset_mask` that removes all values that are masked except on nodata values? This would be useful both for interacting with `rasterio` and for easily manipulating the masked array (adding mask is fine, but removing super-imposed ones not so much).

**Comment by adehecq** [comment]
> @adehecq Should we close this? I'm not sure we want to force values that are masked as nodata for many reasons (different types of masking super-imposed):
> 
>     * if we want to keep masking the Raster for other reasons (unstable terrain),
> 
>     * if we want to find the non-finite values in the data compared to nodata values for debugging reasons.
> 
> 
> The comment above lists the 3 options for manipulating the data safely (ideally, `.data.data` should never be modified manually except for expert use).
> 
> But I'm thinking maybe we should have a function `reset_mask` that removes all values that are masked except on nodata values? This would be useful both for interacting with `rasterio` and for easily manipulating the masked array (adding mask is fine, but removing super-imposed ones not so much).

I'm not sure I get that function. You mean that values that are masked, but not set to nodata would be unmasked?
Can't we actually do that with set_nodata now? (although of course it's not super transparent)
I would say, we don't add this to the issue list until we actually need it. No need to be too pro-active on new features, we need to focus on existing bugs and feature requests 😉 I feel that we've spent a lot of time in the past on features that in the end are not really used. What do you think?

And yes, ok to close the issue!

**Comment by rhugonnet** [comment]
Perfect for closing the issue :+1: 

For `reset_mask`, it would be for instance for:

```python
rst.set_mask(glacier_outlines)

# some amazing calculations on rst

#now i want to reuse rst with its default nodata mask without having to reload the data again
rst.reset_mask()
```

**Comment by rhugonnet** [comment]
It's not a priority feature, for sure!
But I can see it being used in our xDEM example, when we want to feed a masked `ddem` object to error functions (excluding glacier terrain), and then re-compute things on the entire `ddem` (with glacier terrain)

**Comment by adehecq** [comment]
Yes I see. I think at the moment most of the functionalities work on the flattened array or with a `inlier_mask` for coreg functions. So in that case, it's not necessary to mask the raster itself.
The issue I see with your example is how to handle rasters that already have masked values. Would reset_mask unmask all values or the "last" ones and how do we identify the "last" ones?
Feel free to add it to the feature enhancement list, we can always discuss it when we write our release schedule.
