### ISSUE TITLE
Consistently test `environment.yml` and `dev-environment.yml`

### ISSUE THREAD

**Issue by rhugonnet** [GlacioHack/geoutils#296]
**Problem common to GeoUtils and xDEM:**

Right now, during CI, we have no way of verifying that `environment.yml` actually works with the package because we use directly `dev-environment.yml`, which is needed in order to consistently reproduce the environment locally. It would lose a lot of time to test both.

One solution could be, during CI:

1. We install `environment.yml` first,
2. We run `python -c "import xdem"` to check that there are no error when importing the package with `environment.yml`,
3. We also run `flake8` there,
4. (Tricky point) We compute the difference between `dev-environment.yml` and `environment.yml` (separating pip and conda channels if necessary),
5. We update the CI environment with the packages specific to `dev-environment.yml`,
6. We run the tests and documentation building of CI normally.

**Comment by adehecq** [comment]
> (Tricky point) We compute the difference between `dev-environment.yml` and `environment.yml` (separating pip and conda channels if necessary),

You can use `conda env update -f dev-environment.yml`, no need to calculate the difference yourself.
