### ISSUE TITLE
Improve correspondence to 'recommended [GitHub] community standards'

### ISSUE THREAD

**Issue by atedstone** [GlacioHack/GeoUtils#34]
E.g. contributors page, issues template...

**Comment by erikmannerfelt** [comment]
I see that this has been mentioned in four PRs now! Is this solved or are there still things to fix?

**Comment by adehecq** [comment]
> I see that this has been mentioned in four PRs now! Is this solved or are there still things to fix?

According to https://github.com/GlacioHack/GeoUtils/community, there are still a few things that do not follow the community standard...
