### ISSUE TITLE
Floating precision of `rio.transform` in `Raster.reproject()` when passing both `dst_bounds` and `dst_res` (or `dst_size`)

### ISSUE THREAD

**Issue by rhugonnet** [GlacioHack/geoutils#357]
See #356
This specific case is not fixed after #354.

**Comment by adehecq** [comment]
To reproduce the error, with the dataset provided in #354 at [this link](https://drive.google.com/file/d/10usaitjrvmhAgywB_3wPOGDGWJZ8iVnT/view?usp=share_link):
```
import geoutils as gu
rst = gu.Raster("N62E010_FABDEM_V1-0.tif")
tmp = rst.reproject(dst_crs="EPSG:32633")
test = tmp.reproject(dst_res=(20, 20), dst_bounds=tmp.bounds)
print(test.res)
```
-> output resolution is (19.99999999999999, 20.0) instead of (20, 20).
