### ISSUE TITLE
Deprecated pyproj argument

### ISSUE THREAD

**Issue by adehecq** [GlacioHack/geoutils#376]
At [this line](https://github.com/GlacioHack/geoutils/blob/18e0d11635eb2c6ab214ce5bcb4d3bffa9687620/geoutils/projtools.py#L308), the argument `skip_equivalent` of pyproj.transformer.from_crs is deprecated since version 3.1 and removed since 3.4.0 (see [here](https://pyproj4.github.io/pyproj/stable/history.html#id2)) .
It's a bit unclear to me if `skip_equivalent` is the default now... The change in pyproj is here: https://github.com/pyproj4/pyproj/pull/824

**Comment by rhugonnet** [comment]
Yes, it is now the default! So nothing to do except remove, will close this in the next PR.
