### ISSUE TITLE
When saving mask, fails due to dtype = 'bool'

### ISSUE THREAD

**Issue by Elizabethcase** [GlacioHack/geoutils#379]
**Describe the bug**
Saving a mask fails. According to the documentation (https://geoutils.readthedocs.io/en/stable/mask_class.html), I think it should automatically convert the bool dtype to numpy.uint8.

**To Reproduce**
```
outlines_nlcd = gu.Vector(path_to_nlcd)
inlier_mask_nlcd = outlines_nlcd.create_mask(reference_demr)
inlier_mask_all = nlier_mask_nlcd
```

**Expected behavior**
The mask saves as numpy.uint8 dtype, and can be viewed in black/white.

**System (please complete the following information):**
 - OS: macos Ventura
- geoutils v0.0.12

![image](https://github.com/GlacioHack/geoutils/assets/5726652/9cd97f21-64a0-477f-852d-9e4ba81d3d34)

**Comment by rhugonnet** [comment]
Thanks for reporting this @Elizabethcase, now fixed in #380!
I'll publish a new release of GeoUtils soon to update directly from `conda` :slightly_smiling_face:
