### ISSUE TITLE
Raster.reproject returns None if dst_bounds is set

### ISSUE THREAD

**Issue by adehecq** [GlacioHack/GeoUtils#40]
This is because of an improper use of the Raster.crop method, which does not return a data set but update in place.
https://github.com/GlacioHack/GeoUtils/blob/68542e008d685fb9a01ae57d4e4f2befdf2120ae/geoutils/georaster.py#L425

**Comment by iamdonovan** [comment]
We could add an update=True parameter to Raster.crop(), which would update in-place if True, or return a new Raster object if False.
