### ISSUE TITLE
Raster.show() does not always function as expected

### ISSUE THREAD

**Issue by atedstone** [GlacioHack/geoutils#407]
**Describe the bug**
Sometimes Raster.show() fails to identify an appropriate axis/figure on which to plot:

```python
File ~/opt/miniconda3/envs/ee/lib/python3.11/site-packages/geoutils/raster/raster.py:2479, in Raster.show(self, index, cmap, vmin, vmax, alpha, cbar_title, add_cbar, ax, return_axes, **kwargs)
   2476         ax0 = plt.gca()
   2477     # Otherwise, get first axis
   2478     else:
-> 2479         ax0 = plt.gcf().axes[0]
   2480 elif isinstance(ax, str) and ax.lower() == "new":
   2481     _, ax0 = plt.subplots()

IndexError: list index out of range
```

**To Reproduce**

1. In a JupyterLab notebook, use `%matplotlib widget`
2. `myraster.show()`
3. `plt.figure()`
4. `myraster.show()` - fails

**Expected behavior**
The second `.show()` operation should plot the image in the new figure.

**System (please complete the following information):**
 - OS: OSX
 - Environment: geoutils 0.0.11, Python 3.11

**Comment by adehecq** [comment]
Here is a MWE:
```
import geoutils as gu
import matplotlib.pyplot as plt
rst = gu.Raster(gu.examples.get_path("everest_landsat_b4"))
plt.figure()
rst.show()
```
-> fails with "IndexError: list index out of range"

**Comment by adehecq** [comment]
Andrew, a quick fix to that is to run `fig, ax = plt.subplots()` instead of `plt.figure()`.
