### ISSUE TITLE
Homogenize arguments: `inplace` default of ops (`reproject`, `crop`) and georeferenced args (`ref`, `dst_ref`, etc...)

### ISSUE THREAD

**Issue by rhugonnet** [GlacioHack/geoutils#432]
Two problems linked to the default arguments of our functions:

1. It's a bit un-intuitive that some operations would be inplace (`crop`) and others not (`reproject`).

We should probably do the same done by NumPy, Xarray and Pandas: never do inplace, and leave to the user to do it themselves by doing:
```python
raster = raster.crop(mycropgeom)
```
If they want to.

2. Arguments that do the same thing have different names in different functions.

For instance the "match-reference" argument: `dst_ref`, `ref`, etc... Same for many other arguments of functions of `Raster` and `Vector` (`dst_shape`, `size`, `rst_shape`, etc).

The sooner we homogenize the API, the better, otherwise it will be a hard change for users or would have to stay inconsistent for a long time! And doing it before mirroring the API in the Xarray accessor #383 would be great! :smiley: 
So, I think is a top priority we should take care off soon! Was already listed but also a bit lost in the long list here: https://github.com/GlacioHack/geoutils/issues/361.

**Maybe we should start a Google Docs to converge towards the arguments names that are the most intuitive to use everywhere**? 
What do you think @adehecq @atedstone @erikmannerfelt?

**Comment by adehecq** [comment]
Overall I agree with both suggestions.
We can put this in a Google Doc, but ultimately we should maybe summarize this in a Wiki page, so we remember what was decided?

**Comment by atedstone** [comment]
I also agree with both suggestions. I would prefer a wiki page over a Google Doc, but we can also simply add these information to CONTRIBUTING.md so that everything important about development is in one place?

**Comment by rhugonnet** [comment]
Closed by #440, #445 and #449
