### ISSUE TITLE
Remove `src_nodata` from `Raster.reproject()`

### ISSUE THREAD

**Issue by atedstone** [GlacioHack/geoutils#441]
The proposal is to remove the ability to force a source `nodata` value in `Raster.reproject()`. 

Instead, we would instruct users to in the docstring that, to use a different nodata, use `raster.set_nodata` before reproject. 

See discussion in Jan 2024 hack GDoc for more info.

**Comment by rhugonnet** [comment]
The operation on `Mask` works because we always convert the `bool` array to `uint8`, then perform the operation, then convert back. This is done for all ops, to circumvent any nodata issues (nodata is not an attribute of `Mask`). 

Is this still an issue?

**Comment by adehecq** [comment]
> The operation on `Mask` works because we always convert the `bool` array to `uint8`, then perform the operation, then convert back. This is done for all ops, to circumvent any nodata issues (nodata is not an attribute of `Mask`).
> 
> Is this still an issue?

Yes, the operation can work on Masks, that's not the problem. The problem would arise if we remove `src_nodata` as suggested in this issue. Therefore, maybe we should close that issue and leave it as it is?

**Comment by rhugonnet** [comment]
What about just renaming the argument `force_source_nodata` then? (because `src_` is not used anywhere else in `Raster`, and nodata is usually defined so it really is a "forcing" operation)
I can do this while addressing #449 and #445

**Comment by adehecq** [comment]
> What about just renaming the argument to `force_source_nodata` then? (because `src_` is not used anywhere else in `Raster`, and nodata is usually defined so it really is a "forcing" operation) I can do this while addressing #449 and #445

nodata is defined, unless it is None, which is the case for our landsat examples. But I'm fine with your suggestion if you think that's clearer.
