### ISSUE TITLE
RunetimeWarning raised by Raster.astype when data contains Nans

### ISSUE THREAD

**Issue by adehecq** [GlacioHack/geoutils#494]
`Raster.astype` raises a warning when the input data contains NaNs (even if hidden by the mask) when the cast type is not compatible with NaNs.
This is rather annoying as there is no other solution to silent this warning than to modify self.data.data to replace NaNs to another value. Using `Raster.set_mask` or `Raster.set_nodata` does not update self.data.data. 

Example to reproduce:
```
import geoutils as gu
import numpy as np
raster = gu.Raster(gu.examples.get_path("exploradores_aster_dem"))
raster.data.data[raster.data.data == -9999] = np.nan
test = raster.astype("uint16")
```
raises "RuntimeWarning: invalid value encountered in cast".

**Comment by rhugonnet** [comment]
I'm not sure if this is really an issue... NumPy will warn the same thing if you modify your masked array that has NaNs to another masked array with type not supporting NaNs using its `astype`, no? And so we should also keep it to stay consistent with NumPy?

**Comment by rhugonnet** [comment]
Just tested this, NumPy indeed raises the error the same:
```python
raster.data.astype("uint16")
```
```
RuntimeWarning: invalid value encountered in cast
```
So we're simply consistent with NumPy behaviour.

And if you mask the nodata values instead of setting NaN (same behaviour for all other operations):
```python
import geoutils as gu
import numpy as np
raster = gu.Raster(gu.examples.get_path("exploradores_aster_dem"))
raster.data[raster.data.data == -9999] = np.ma.masked
raster.astype("uint16")
```
Then we convert fine and raise a warning about loss of information:
```
/home/atom/code/devel/libs/geoutils/geoutils/raster/raster.py:1548: UserWarning: dtype conversion will result in a loss of information. float32 is the minimum type to represent the data.
  f"{rio.dtypes.get_minimum_dtype(self.data)} is the minimum type to represent the data."
```
So that behaviour is consistent, we can close!
