### ISSUE TITLE
Check what tools can be imported from pygeotools

### ISSUE THREAD

**Issue by adehecq** [GlacioHack/geoutils#51]
Go through David's tools and see what useful functionalities could be implemented
https://github.com/dshean/pygeotools

**Comment by rhugonnet** [comment]
Nearly 3 years later, what I see in `pygeotools` that we are missing:
- A "crop_nodata" function: (remove rows/cols containing only NoData from raster margins),
- Merge shapefiles together (even though this should be supported through geopandas, we could have a parent function),
- Filters (Gauss, rolling median, high pass, etc).
Closing this and opening issues for what is not already there!

**Comment by rhugonnet** [comment]
Yes, it should be working since I wrote https://github.com/GlacioHack/geoutils/blob/main/tests/test_geoviewer.py.

We'll have to see if we add CLI tool support to both GeoUtils and xDEM at some point (https://github.com/GlacioHack/geoutils/issues/54)
