### ISSUE TITLE
Remove `rioxarray` optional import logic now that it is a main dependency

### ISSUE THREAD

**Issue by rhugonnet** [GlacioHack/geoutils#513]
This was forgotten!

**Comment by adehecq** [comment]
And did we actually need to make it a main dependency? It is only used in one function, would it not make more sense to keep it as optional?
Or will you need it more in ongoing/future PRs?

**Comment by rhugonnet** [comment]
Yes that's why, it has to be a main dependency for the Xarray accessor in the works :wink:
