### ISSUE TITLE
Re-organize raster and vector functionalities as separate functions

### ISSUE THREAD

**Issue by rhugonnet** [GlacioHack/geoutils#539]
Already mentioned when discussing #383, we need to move out all function of `Raster` and `Vector` to live outside the class, both to facilitate the Xarray accessor and tests.

Here's an idea of structure, adding new modules:

In _geoutils/_: 

_raster/_
**-- accessor.py** (Xarray raster accessor)
**-- distance.py** (proximity)
**-- georef.py** (for reproject, crop)

_vector/_
**-- geometric.py** (buffer_with_overlap)
**-- georef.py** (reproject, crop)

**raster_vector_interface.py** (rasterize, polygonize, create_mask, to_pointcloud)

**Comment by adehecq** [comment]
I guess all these submodules would never have to be called by the user, as all the functions would be implemented as class methods? If so, this sounds good !

**Comment by rhugonnet** [comment]
Yes exactly!
