### ISSUE TITLE
Check if rio plotting duplicates data loading

### ISSUE THREAD

**Issue by rhugonnet** [GlacioHack/GeoUtils#55]
@rhugonnet have you looked at my earlier comment? I'm concerned that using rasterio's plotting function might load the data a second time, which is not ideal for large data set...

_Originally posted by @adehecq in https://github.com/GlacioHack/GeoUtils/issues/37#issuecomment-738100402_

**Comment by adehecq** [comment]
According to rasterio's code here https://github.com/mapbox/rasterio/blob/a1cb28a77ebca80c8a804f24d09350e02ed9bf63/rasterio/plot.py#L91
The dataset is loaded into memory, therefore possibly duplicating the data. Better to provide the loaded data (np array) directly to show, rather than dataset.
