### ISSUE TITLE
Documentation API not always showing up properly

### ISSUE THREAD

**Issue by adehecq** [GlacioHack/geoutils#592]
On this page for example, the list of parameters is broken, probably due to line breaks: https://geoutils.readthedocs.io/en/stable/gen_modules/geoutils.Raster.interp_points.html#geoutils.Raster.interp_points

**Comment by rhugonnet** [comment]
That's my fault, Sphinx was throwing a warning about this line indent that I didn't fix before merging. Now should be good, and was only one of two (fixed in #597).
