### ISSUE TITLE
The nodata=0 of integer raster types gets wrongly updated to the default (e.g. 65535 for uint16 types) after a stack_raster operation

### ISSUE THREAD

**Issue by axeldolce** [GlacioHack/geoutils#608]
**Describe the bug**
If two rasters of integer types, for instance uint16, and nodata=0 are stacked via the **stack_raster** operation, after the stack both the original rasters and the output raster have nodata which has been wrongly updated to the integer default, for instance 65535.

**To Reproduce**
One can reproduce the behaviour with this code:

```python
import numpy as np
from affine import Affine
from geoutils import Raster
from geoutils.raster import stack_rasters
from pyproj import CRS
from rasterio.enums import Resampling

nodata = 0
filling_value = 65534

# Define a first raster with only 1s
shape = (10, 10)
data_int = np.ones(shape).astype(np.uint16)
data_mask = np.zeros(shape).astype(bool)
data_masked = np.ma.masked_array(data=data_int, mask=data_mask, fill_value=nodata)
r1 = Raster.from_array(
    data=data_masked,
    transform=Affine(
        1000.0,
        0.0,
        1_000_000.0,
        0.0,
        -1000.0,
        1_000_000.0,
    ),
    crs=CRS.from_string("EPSG:3857"),
    nodata=nodata,
)

# Define a second raster with only 5s and the value defined above
shape = (10, 10)
data_int = (np.ones(shape) * 5).astype(np.uint16)
data_int[:5, :5] = filling_value
data_mask = np.zeros(shape).astype(bool)
data_masked = np.ma.masked_array(data=data_int, mask=data_mask, fill_value=nodata)

r2 = Raster.from_array(
    data=data_masked,
    transform=Affine(
        1000.0,
        0.0,
        1_000_000.0,
        0.0,
        -1000.0,
        1_000_000.0,
    ),
    crs=CRS.from_string("EPSG:3857"),
    nodata=nodata,
)

# Stack the two rasters
rstacked = stack_rasters(
    rasters=[r1, r2],
    progress=False,
    resampling_method=Resampling.nearest,
)
# rstacked.set_nodata(nodata) # Temporary FIX valid for all filling_values != 65535

print("r1 unique:", np.unique(r1))
print("r1 nodata:", r1.nodata)
print("r2 unique:", np.unique(r2))
print("r2 nodata:", r2.nodata)
print("rstacked unique:", np.unique(rstacked))
print("rstacked nodata:", rstacked.nodata)
```
which outputs
```
r1 unique: [1]
r1 nodata: 65535
r2 unique: [5 65534]
r2 nodata: 65535
rstacked unique: [    1     5 65534]
rstacked nodata: 65535
```
Here it is clear that the nodata=0 has been updated to nodata=65535. This effect is also probably due to the **stack_raster** operation since, if skipped, the original rasters still have their original nodata value:
```
r1 unique: [1]
r1 nodata: 0
r2 unique: [5 65534]
r2 nodata: 0
```
This problem seems to be present only when nodata=0, because if nodata is equal to any other value, the original nodata value gets correctly maintained after the stack. 

A special case where this problem is especially problematic is if filling_value=65535 because in that case the output is:
```
r1 unique: [1]
r1 nodata: 65535
r2 unique: [5 --]
r2 nodata: 65535
rstacked unique: [1 5 --]
rstacked nodata: 65535
```
so that the values in the second raster equal to 65535 are now mixed with the mask and therefore lost.

**Expected behavior**
The expected behaviour is what happens with all other nodata values other than zero, which is to keep the original nodata value after the stack. A possible temporary solution for this problem could be to uncomment the commented line:
```python
# rstacked.set_nodata(nodata) # Temporary FIX valid for all filling_values != 65535
```
but this is only feasable if the filling_value is not 65535, because otherwise the problem remains.

**System:**
 - OS: WSL2 on Windows 11
 - Environment: venv installed via pip, geoutils at version 0.1.9

**Additional context**
Hopefully this is an actual bug and not the expected bahaviour. Thanks again to the maintainers if they can address this.

**Comment by rhugonnet** [comment]
@axeldolce Thanks for this great reproducible example! This is definitely not intended behaviour.

I think I found the issue, here:
https://github.com/GlacioHack/geoutils/blob/1289d3fa21466c5ee727ac02ad3fe35e148690c9/geoutils/raster/multiraster.py#L176

Using `reference_raster.nodata` as a conditional is originally intended to return `False` when the nodata is undefined with `None`, but in this case it'll actually also be understood as `False` when it's an integer nodata value equal to 0 (and only in that specific case, quite incredible that you identified it!).

Replacing that line by:
```python
        nodata = reference_raster.nodata if not None else gu.raster.raster._default_nodata(reference_raster.data.dtype)
```
seems to do the job for your example (which I will add to the package's tests :wink:).

What worries me the most, however, is the fact that the `.nodata` attributes of both `r1` and `r2` got updated while they were passed to another operation. This should normally never be the case, and I don't yet see how this conditional operation would have been responsible for that. There might something else there.
I'll look a bit more into it, to check how this occured...

Thanks again!

**Comment by rhugonnet** [comment]
Alright, I've found why `r1.nodata` and `r2.nodata` got updated. It is another bug specific to that function, for a rare occurrence case.

The details:
Before stacking, the function `stack_rasters()` reprojects all rasters to the same reference through `reproject()`. In the case where the georeferenced of the reference (CRS, transform) is exactly the same as the input, `reproject()` raises a `UserWarning` saying that no operation is needed (or just a nodata changed through `.set_nodata()`) and returns `self`. But in `stack_rasters()`, we silence this warning with the option `silent=True`, and then this (possibly) `self`-returned raster is modified with `set_nodata()`.

So simply need to add a check if the georeferenced grid is equal, and copy the raster before re-setting its nodata. I'll do this in #609.

**Comment by axeldolce** [comment]
Thanks for the reply! I'm glad it was a quick fix. I stumbled upon this because I often work with integer land cover rasters, and I have the habit of keeping the nodata to zero so when I need to merge multiple rasters I can use something like np.max as merging algorithm. So it really was a peculiar coincidence :) 

I was also a bit surprised by the update of the input rasters after the stack operation, thankfully that was also fixable!

Thanks again and all the best,
Axel
