### ISSUE TITLE
Add downsampling functionality

### ISSUE THREAD

**Issue by atedstone** [GlacioHack/GeoUtils#67]

**Comment by adehecq** [comment]
Can load downsampled data with ds.read's option out_shape: https://rasterio.readthedocs.io/en/latest/api/rasterio._warp.html?highlight=read#rasterio._warp.WarpedVRTReaderBase.read

However, the output data will have a different size than metadata, so this will break for example data.setter.

**Comment by adehecq** [comment]
So basically the question is: should we save the downsampled array in self.data or not? I can see some issues later with plotting or cropping. 
But it would be great to be able to load a subset and for example reproject it (or any other Raster's functionality).
What do you think @atedstone @rhugonnet ?

**Comment by adehecq** [comment]
Implemented in #99
