### ISSUE TITLE
How to expose demo data sets

### ISSUE THREAD

**Issue by atedstone** [GlacioHack/GeoUtils#70]
e.g. for use in notebooks etc, it would be good to streamline the opening/paths to the demo datasets. These can be the same as those used in testing, but we shouldn't need to rely on the test suite to tell us where demo data is....

**Comment by adehecq** [comment]
We should probably do something similar to geopandas: https://github.com/geopandas/geopandas/blob/master/geopandas/datasets/__init__.py

**Comment by adehecq** [comment]
Solved by #79 and #84
