### ISSUE TITLE
Branch naming and require forks

### ISSUE THREAD

**Issue by atedstone** [GlacioHack/GeoUtils#75]
This is advance warning that once Hack number 2 is over there will be some administrative changes:

- `dev` renamed to `master`
- `main` renamed to `stable`
- no more pushing to branches of the main repository
- all commits must be made in fork of the main repository, and then a PR opened against `master`. 
- PR merges into `master` will probably mandate "squash and merge" commits (I may need to discuss further with @fmaussion on this)

What does this mean for you?

- Delete your local machine copy of `geoutils`
- On GitHub, fork the GlacioHack `geoutils` repo to your personal account
- `git clone` your fork
- always work in feature branches
- `git push` back to your own fork
- then open a PR for the branch on your own fork to be merged into `master`.

Amongst other things, this will simplify the main repository's history, and bring us more into line with "best practises" adopted elsewhere.

**Comment by rhugonnet** [comment]
Great summary, thanks a lot. Will do.
Learning quite a bit on best practices!
