### ISSUE TITLE
Implement the 'clip' method

### ISSUE THREAD

**Issue by adehecq** [GlacioHack/geoutils#81]
Currently, the clip method is empty

**Comment by atedstone** [comment]
How is clipping different to cropping? (There's a crop() method)

**Comment by adehecq** [comment]
Good question! I didn't realize the (empty) clip function was in georaster. I think it was intended for geovector.py. Clipping a set of shapes to a raster extent for example.

**Comment by atedstone** [comment]
@adehecq can we close this issue?

**Comment by adehecq** [comment]
No, still need to implement this for geovector.
