### ISSUE TITLE
Crop() method fails if image data not loaded

### ISSUE THREAD

**Issue by atedstone** [GlacioHack/GeoUtils#87]
The crop() method notionally supports cropping of an image not yet loaded into memory (i.e. self.isLoaded logic). However, it fails if no image data have been loaded.

**Comment by adehecq** [comment]
What do you mean by "it fails"?
For me, it works even without loading the data, but then of course the data is not loaded. This is fixed by loading the data afterward, e.g.:
```
In [182]: r = gr.Raster(datasets.get_path("landsat_B4"),load_data=False)

In [183]: r2 = gr.Raster(datasets.get_path("landsat_B4_crop"),load_data=False)

In [184]: r.bounds
Out[184]: BoundingBox(left=478000.0, bottom=3088490.0, right=502000.0, top=3108140.0)

In [185]: r.crop(r2)

In [186]: r.bounds
Out[186]: BoundingBox(left=484060.0, bottom=3098030.0, right=502000.0, top=3103250.0)

In [187]: r.data

In [188]: r.load()

In [189]: r.data
Out[189]: 
masked_array(
  data=[[[109,  98, 104, ..., 182, 118,  92],
         [112, 109, 107, ..., 100,  92,  89],
         [111, 115, 105, ...,  88,  90,  91],
         ...,
         [230, 188, 149, ...,  64,  65,  64],
         [208, 201, 198, ...,  68,  64,  62],
         [179, 173, 193, ...,  75,  75,  75]]],
  mask=False,
  fill_value=999999,
  dtype=uint8)
```

**Comment by adehecq** [comment]
We could add a self.load at the end of crop to make it more intuitive? But I'm not sure it's what we want, is it?

**Comment by adehecq** [comment]
What's your opinion on this Andrew?

**Comment by atedstone** [comment]
OK, I don't know what was going wrong before, but I can replicate @adehecq 's comment using 1dd489b, so closing this issue.
